Use `generate-changelog` action in `java-gradle-release`
bakdata/ci-templates pull request #146
Opened 2023-09-21 16:29 UTC by MichaelKora

2023-09-21 19:01 UTC, yannick-roeder requested changes

2023-09-29 08:51 UTC, yordanovsstoyan submitted a review, later dismissed

2023-09-29 09:53 UTC, yordanovsstoyan submitted a review, later dismissed

2023-09-29 10:22 UTC, torbsto submitted a review, later dismissed

2023-09-29 10:22 UTC, torbsto commented on .github/workflows/java-gradle-release.yaml
> +
Any reason for this empty line? There are none between all other parameters

2023-09-29 10:22 UTC, torbsto commented on actions/java-gradle-release/action.yaml
> +  changelog-file:
Missing documentation?

2023-09-29 10:22 UTC, torbsto commented on .github/workflows/java-gradle-release.yaml
> +      changelog-file:
Missing documentation

2023-09-29 10:22 UTC, torbsto commented on actions/java-gradle-release/action.yaml
> +      uses: bakdata/ci-templates/actions/changelog-generate@chore/automatic-changelog
Please update

2023-09-29 10:22 UTC, torbsto commented on actions/java-gradle-release/action.yaml
> +        fetch-reviewers: "true"
Why do we want this? Currently the changelog only contains the authors

2023-10-04 13:17 UTC, yannick-roeder requested changes

2023-10-04 13:17 UTC, yannick-roeder commented on actions/java-gradle-release-github/action.yaml
>          gradle-cache: ${{ inputs.gradle-cache }}
Java Gradle Setup is not needed anymore in this action then

2023-10-05 08:19 UTC, yannick-roeder requested changes

2023-10-09 08:01 UTC, yannick-roeder commented on actions/java-gradle-release/action.yaml
> -        git push --follow-tags origin ${{ github.event.repository.default_branch }}
Remember that we only want to push the tag here, the GitHub release is created from CI running on the tag later

2023-10-09 09:39 UTC, yannick-roeder submitted a review, later dismissed

2023-10-09 09:40 UTC, yannick-roeder commented on .github/workflows/java-gradle-release.yaml
> +        uses: bakdata/ci-templates/actions/java-gradle-release@1.35.2
This is not up to date anymore

2023-10-09 11:57 UTC, yannick-roeder requested changes

2023-10-11 09:23 UTC, yannick-roeder approved these changes

2023-10-11 09:35 UTC, merged