feat: block java release on playground repo
bakdata/ci-templates pull request #207
Opened 2024-08-05 22:32 UTC by DerTiedemann

Make sure playground repos never release a java project on accident

2024-08-06 07:25 UTC, yannick-roeder requested changes

2024-08-06 07:25 UTC, yannick-roeder commented on actions/java-gradle-publish/action.yaml
> +      if: ${{ !startsWith(github.ref, 'refs/tags/') && !contains(github.repository, 'playground') }}
Looks good, can you also do this for the assessment an publication of code quality to sonaqube?
https://github.com/bakdata/ci-templates/blob/main/actions/java-gradle-assess-code-quality/action.yaml#L72
https://github.com/bakdata/ci-templates/blob/main/actions/java-gradle-assess-code-quality/action.yaml#L80

2024-09-02 08:26 UTC, yannick-roeder approved these changes

2024-11-19 09:42 UTC, merged

2025-01-22 13:12 UTC, philipp94831 commented
@DerTiedemann @yannick-roeder As we have reverted this due to syntax errors, please don't forget to reimplement it. I also feel like it is better to block this on a workflow level instead of actions as this is more related to our setup and actions are something used across projects (and even people we don't know)