Update deprecated NodeJS actions
bakdata/ci-templates pull request #215
Opened 2024-11-08 14:22 UTC by yannick-roeder

2024-11-08 14:24 UTC, yannick-roeder commented on .github/workflows/_format.yaml
> +      - uses: bakdata/ci-templates/actions/checkout@ft/nodejs-action-update
TODO: Pre-bump

2024-11-08 14:34 UTC, JakobEdding requested changes

2024-11-08 14:36 UTC, JakobEdding approved these changes

2024-11-08 14:36 UTC, JakobEdding commented on docs/actions/bump-version/README.md
> +  - uses: bakdata/ci-templates/actions/checkout@main
Ok, I just saw that in the project root's README we also have it like this so it's fine for me. Maybe we can open an issue to template the concrete latest tag into the README or docs.

2024-11-11 10:42 UTC, JakobEdding approved these changes

2024-11-11 14:53 UTC, merged